spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydatabase
      username: root
      password: example
      authentication-database: admin
  graphql:
    graphiql:
      enabled: true
server:
  port: ${PORT:8080}